# В файле /dedrarion/src/main/resources/META-INF/mods.toml

modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPL v3"

[[mods]]
modId="dedrarion"
version="1.0.0"
displayName="Dedrarion Adventures"
authors="Haru (Hivens)"
description='''Core API for Dedrarion Adventures modules.'''

[[dependencies.dedrarion]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dedrarion]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"