modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"

[[mods]]
modId="dedrarion"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.dedrarion]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dedrarion]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.dedrarion]]
modId="jei"
mandatory=false
versionRange="[15.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.dedrarion]]
modId="jeresources"
mandatory=false
versionRange="[1.4.0,)"
ordering="NONE"
side="BOTH"
